/**
*********************************************************************************************************
*               Copyright(c) 2016, Realtek Semiconductor Corporation. All rights reserved.
**********************************************************************************************************
* @file     vendor_tp_service.c
* @brief    simple BLE profile source file.
* @details  Demonstration of how to implement a self-definition profile.
* @author
* @date     2016-02-18
* @version  v0.1
*********************************************************************************************************
*/
#include "trace_app.h"
#include <string.h>
#include "vendor_pxpext_service.h"
#include "gap.h"


/********************************************************************************************************
* local static variables defined here, only used in this source file.
********************************************************************************************************/
T_SERVER_ID vendor_pxpext_service_id;
uint8_t test_rw_value[255] = {0};
uint8_t test_rw_value_len = 0;

/**<  Function pointer used to send event to application from simple profile. Initiated in vendor_tp_service_add. */
//static P_FUN_SERVER_GENERAL_CB pfn_vendor_pxpext_service_cb = NULL;

const uint8_t   GATT_UUID128_PXPEXT_SERVICE[16] =
{0xA6, 0xF6, 0xF6, 0x07, 0x4D, 0xC4, 0x9D, 0x98, 0x6D, 0x45, 0x29, 0xBB, 0xD0, 0xFF, 0x00, 0x00};
#define GATT_UUID128_CHAR_PARAM   0xA6, 0xF6, 0xF6, 0x07, 0x4D, 0xC4, 0x9D, 0x98, 0x6D, 0x45, 0x29, 0xBB, 0xD1, 0xFF, 0x00, 0x00,

static const T_ATTRIB_APPL vendor_pxpext_service_tbl[] =
{
    {
        (ATTRIB_FLAG_VOID | ATTRIB_FLAG_LE),
        {
            LO_WORD(GATT_UUID_PRIMARY_SERVICE),
            HI_WORD(GATT_UUID_PRIMARY_SERVICE),
        },
        UUID_128BIT_SIZE,
        (void *)GATT_UUID128_PXPEXT_SERVICE,
        GATT_PERM_READ
    },

    {
        ATTRIB_FLAG_VALUE_INCL,
        {
            LO_WORD(GATT_UUID_CHARACTERISTIC),
            HI_WORD(GATT_UUID_CHARACTERISTIC),
            GATT_CHAR_PROP_READ | GATT_CHAR_PROP_WRITE,
        },
        1,
        NULL,
        GATT_PERM_READ
    },

    {
        ATTRIB_FLAG_VALUE_APPL | ATTRIB_FLAG_UUID_128BIT,
        {
            GATT_UUID128_CHAR_PARAM
        },
        0,
        NULL,
        GATT_PERM_READ | GATT_PERM_WRITE
    },

};




/**
 * @brief read characteristic data from service.
 *
 * @param service_id          ServiceID of characteristic data.
 * @param iAttribIndex          Attribute index of getting characteristic data.
 * @param iOffset                Used for Blob Read.
 * @param piLength            length of getting characteristic data.
 * @param ppValue            data got from service.
 * @return Profile procedure result
*/
T_APP_RESULT  vendor_pxpext_service_attr_read_cb(uint8_t conn_id, T_SERVER_ID service_id,
                                                 uint16_t iAttribIndex, uint16_t iOffset, uint16_t *piLength, uint8_t **ppValue)
{
    T_APP_RESULT  wCause  = APP_RESULT_SUCCESS;

    switch (iAttribIndex)
    {
    default:
        APP_PRINT_INFO1("vendor_tp_service_attr_read_cb, iAttribIndex=%d", iAttribIndex);
        *ppValue = test_rw_value;
        *piLength = test_rw_value_len;
        break;
    }

    return (wCause);
}


/**
 * @brief write characteristic data from service.
 *
 * @param ServiceID          ServiceID to be written.
 * @param iAttribIndex          Attribute index of characteristic.
 * @param wLength            length of value to be written.
 * @param pValue            value to be written.
 * @return Profile procedure result
*/
T_APP_RESULT vendor_pxpext_service_attr_write_cb(uint8_t conn_id, T_SERVER_ID service_id,
                                                 uint16_t iAttribIndex, T_WRITE_TYPE write_type, uint16_t wLength, uint8_t *pValue,
                                                 P_FUN_WRITE_IND_POST_PROC *pWriteIndPostProc)
{
    T_APP_RESULT  wCause = APP_RESULT_SUCCESS;
    APP_PRINT_INFO3("vendor_pxpext_service_attr_write_cb, iAttribIndex=%d, wLength = %d, pValue:%b",
                    iAttribIndex,
                    wLength,
                    TRACE_BINARY(wLength, pValue));

    memcpy(test_rw_value, pValue, wLength);
    test_rw_value_len = wLength;
    return wCause;
}


const T_FUN_GATT_SERVICE_CBS vendor_pxpext_service_cbs =
{
    vendor_pxpext_service_attr_read_cb,     // Read callback function pointer
    vendor_pxpext_service_attr_write_cb,    // Write callback function pointer
    NULL                                    // CCCD update callback function pointer
};


/**
  * @brief add Simple BLE service to application.
  *
  * @param[in] pFunc          pointer of app callback function called by profile.
  * @return service ID auto generated by profile layer.
  * @retval service_id
  */
T_SERVER_ID vendor_pxpext_service_add(void *pFunc)
{
    if (false == server_add_service(&vendor_pxpext_service_id,
                                    (uint8_t *)vendor_pxpext_service_tbl,
                                    sizeof(vendor_pxpext_service_tbl),
                                    vendor_pxpext_service_cbs))
    {
        APP_PRINT_ERROR1("vendor_pxpext_service_add: service_id %d", vendor_pxpext_service_id);
        vendor_pxpext_service_id = 0xff;
        return vendor_pxpext_service_id;
    }

//    pfn_vendor_pxpext_service_cb = (P_FUN_SERVER_GENERAL_CB)pFunc;
    return vendor_pxpext_service_id;
}

