#ifndef __PLATFORM_OPTS_BT_H__
#define __PLATFORM_OPTS_BT_H__

#define CONFIG_BT			0

#if CONFIG_BT
#define CONFIG_FTL_ENABLED
#define CONFIG_BT_CONFIG			0
#define CONFIG_BT_AIRSYNC_CONFIG	0
#define CONFIG_BT_PERIPHERAL		0
#define CONFIG_BT_CENTRAL			0
#define CONFIG_BT_SCATTERNET		0
#define CONFIG_BT_BEACON			0
#define CONFIG_BT_FUZZ_TEST			0
#define CONFIG_BT_OTA_CENTRAL_CLIENT					0
#define CONFIG_BT_DATATRANS			0
#define CONFIG_BT_JOYLINK_ADAPTER	0
#define CONFIG_BT_ANCS				0
#define CONFIG_BT_MESH_PROVISIONER	0
#define CONFIG_BT_MESH_DEVICE		0
#define CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE		0
#define CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE			0
#define CONFIG_BT_MESH_CENTRAL							0
#define CONFIG_BT_MESH_PERIPHERAL						0
#define CONFIG_BT_MESH_SCATTERNET						0
#define CONFIG_BT_MESH_PROVISIONER_RTK_DEMO				0
#define CONFIG_BT_MESH_DEVICE_RTK_DEMO					0
#define CONFIG_BT_MESH_TEST								0
#define CONFIG_BT_MESH_DEVICE_MATTER					0
#define CONFIG_BT_MESH_DEVICE_CONFIG					0
#define CONFIG_BT_MESH_PROVISIONER_OTA_CLIENT			0
#define CONFIG_BT_ONLY_WITHOUT_WLAN					0
/* For Google seamless setup FreeRTOS SDK example */
#define CONFIG_BT_GOOGLE_SEAMLESS     0
#endif // CONFIG_BT

#if defined CONFIG_BT_SCATTERNET && CONFIG_BT_SCATTERNET
#undef CONFIG_BT_PERIPHERAL
#undef CONFIG_BT_CENTRAL
#define CONFIG_BT_PERIPHERAL		1
#define CONFIG_BT_CENTRAL			1
#endif

#if defined CONFIG_BT_CENTRAL && CONFIG_BT_CENTRAL
#define CONFIG_BT_WHITE_LIST_TO_FLASH	0
#endif

#if ((defined CONFIG_BT_OTA_CENTRAL_CLIENT && CONFIG_BT_OTA_CENTRAL_CLIENT) || \
	(defined(CONFIG_BT_MESH_PROVISIONER_OTA_CLIENT) && CONFIG_BT_MESH_PROVISIONER_OTA_CLIENT))
#if defined CONFIG_BT_OTA_CENTRAL_CLIENT && CONFIG_BT_OTA_CENTRAL_CLIENT
#define CONFIG_BT_OTA_CENTRAL_CLIENT_SPLIT		0
#endif
#define CONFIG_BT_OTA_CENTRAL_CLIENT_W_REQ_CONFLICT		0
#endif

#if ((defined CONFIG_BT_MESH_PROVISIONER && CONFIG_BT_MESH_PROVISIONER) || \
    (defined CONFIG_BT_MESH_DEVICE && CONFIG_BT_MESH_DEVICE) || \
    (defined CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE && CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE) || \
    (defined CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE && CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE))
#define CONFIG_BT_MESH_USER_API		1
#define CONFIG_BT_MESH_IDLE_CHECK   0
#endif

#if defined CONFIG_BT_MESH_PROVISIONER_RTK_DEMO && CONFIG_BT_MESH_PROVISIONER_RTK_DEMO
#undef CONFIG_BT_CONFIG
#define CONFIG_BT_CONFIG			1
#endif

#if ((defined CONFIG_BT_MESH_PROVISIONER && CONFIG_BT_MESH_PROVISIONER) && (defined CONFIG_BT_MESH_DEVICE && CONFIG_BT_MESH_DEVICE))
#error "CONFIG_BT_MESH_PROVISIONER & CONFIG_BT_MESH_DEVICE can not open at the same time"
#endif

#if ((defined CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE && CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE) && (defined CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE && CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE))
#error "CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE & CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE can not open at the same time"
#endif

#if (((defined CONFIG_BT_MESH_CENTRAL && CONFIG_BT_MESH_CENTRAL) && (defined CONFIG_BT_MESH_PERIPHERAL && CONFIG_BT_MESH_PERIPHERAL)) || \
    ((defined CONFIG_BT_MESH_CENTRAL && CONFIG_BT_MESH_CENTRAL) && (defined CONFIG_BT_MESH_SCATTERNET && CONFIG_BT_MESH_SCATTERNET)) || \
    ((defined CONFIG_BT_MESH_PERIPHERAL && CONFIG_BT_MESH_PERIPHERAL) && (defined CONFIG_BT_MESH_SCATTERNET && CONFIG_BT_MESH_SCATTERNET)) || \
    ((defined CONFIG_BT_MESH_CENTRAL && CONFIG_BT_MESH_CENTRAL) && (defined CONFIG_BT_MESH_PERIPHERAL && CONFIG_BT_MESH_PERIPHERAL) && (defined CONFIG_BT_MESH_SCATTERNET && CONFIG_BT_MESH_SCATTERNET)))
#error "Only one of CONFIG_BT_MESH_CENTRAL, CONFIG_BT_MESH_PERIPHERAL and CONFIG_BT_MESH_SCATTERNET can be enabled"
#endif

#if (defined(CONFIG_BT_MESH_DEVICE_MATTER) && CONFIG_BT_MESH_DEVICE_MATTER)
#if ((defined CONFIG_BT_MESH_PROVISIONER && CONFIG_BT_MESH_PROVISIONER) || \
    (defined CONFIG_BT_MESH_DEVICE && CONFIG_BT_MESH_DEVICE) || \
    (defined CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE && CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE))
#error "only open CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE and then open CONFIG_BT_MESH_DEVICE_MATTER"
#endif
#if ((defined CONFIG_BT_MESH_CENTRAL && CONFIG_BT_MESH_CENTRAL) || \
    (defined CONFIG_BT_MESH_PERIPHERAL && CONFIG_BT_MESH_PERIPHERAL) || \
    (defined CONFIG_BT_MESH_SCATTERNET && CONFIG_BT_MESH_SCATTERNET))
#error "CONFIG_BT_MESH_DEVICE_MATTER or CONFIG_BT_MESH_CENTRAL or CONFIG_BT_MESH_PERIPHERAL or CONFIG_BT_MESH_SCATTERNET not open at the same time"
#endif
#endif

#if (defined(CONFIG_BT_MESH_DEVICE_CONFIG) && CONFIG_BT_MESH_DEVICE_CONFIG)
#if ((defined CONFIG_BT_MESH_PROVISIONER && CONFIG_BT_MESH_PROVISIONER) || \
    (defined CONFIG_BT_MESH_DEVICE && CONFIG_BT_MESH_DEVICE) || \
    (defined CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE && CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE))
#error "only open CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE and then open CONFIG_BT_MESH_DEVICE_CONFIG"
#endif
#if ((defined CONFIG_BT_MESH_CENTRAL && CONFIG_BT_MESH_CENTRAL) || \
    (defined CONFIG_BT_MESH_PERIPHERAL && CONFIG_BT_MESH_PERIPHERAL) || \
    (defined CONFIG_BT_MESH_SCATTERNET && CONFIG_BT_MESH_SCATTERNET))
#error "CONFIG_BT_MESH_DEVICE_CONFIG or CONFIG_BT_MESH_CENTRAL or CONFIG_BT_MESH_PERIPHERAL or CONFIG_BT_MESH_SCATTERNET not open at the same time"
#endif
#endif

#if defined(CONFIG_BT_MESH_PROVISIONER_OTA_CLIENT) && CONFIG_BT_MESH_PROVISIONER_OTA_CLIENT
#if ((defined CONFIG_BT_MESH_PROVISIONER && CONFIG_BT_MESH_PROVISIONER) || \
    (defined CONFIG_BT_MESH_DEVICE && CONFIG_BT_MESH_DEVICE) || \
    (defined CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE && CONFIG_BT_MESH_DEVICE_MULTIPLE_PROFILE))
#error "only open CONFIG_BT_MESH_PROVISIONER_MULTIPLE_PROFILE and then open CONFIG_BT_MESH_PROVISIONER_OTA_CLIENT"
#endif
#if ((defined CONFIG_BT_MESH_CENTRAL && CONFIG_BT_MESH_CENTRAL) || \
    (defined CONFIG_BT_MESH_PERIPHERAL && CONFIG_BT_MESH_PERIPHERAL) || \
    (defined CONFIG_BT_MESH_SCATTERNET && CONFIG_BT_MESH_SCATTERNET))
#error "CONFIG_BT_MESH_PROVISIONER_OTA_CLIENT or CONFIG_BT_MESH_CENTRAL or CONFIG_BT_MESH_PERIPHERAL or CONFIG_BT_MESH_SCATTERNET not open at the same time"
#endif
#endif

#endif // __PLATFORM_OPTS_BT_H__

